### ISSUE TITLE
Module reorg

### ISSUE THREAD

**Issue by smwoodman** [SWFSC/glider-utils#12]
Proposal to rename some modules/move functions around:

- make a new 'gcp' module, for all functions that deal with GCP-specific actions
- move realtime.access_secret_version to 'gcp'
- move utils.gcs_unmount_bucket and utils.gcs_unmount_bucket to 'gcp'
- move realtime.rt_files_mgmt to 'pathutils', and thus delete the realtime module.

@flaimC does this all make sense to you?

**Comment by flaimC** [comment]
Yes, that sounds good!
